#!/usr/bin/env bun
/**
 * Generates src/lib/embedded-skills.gen.ts from the contents of skill/.
 *
 * The skill/ directory is synced from muxinc/mux-skills by the sync-skills
 * workflow. Embedding the files as string constants means every build target
 * (bun run, dist bundle, compiled binary) ships the skills with no runtime
 * filesystem or network dependency.
 *
 * Run with: pnpm run generate:skills
 */
import { readdir } from 'node:fs/promises';
import { join } from 'node:path';

const repoRoot = join(import.meta.dir, '..');
const skillDir = join(repoRoot, 'skill');
const outPath = join(repoRoot, 'src', 'lib', 'embedded-skills.gen.ts');

const entries = await readdir(skillDir, {
  recursive: true,
  withFileTypes: true,
});

const files: Record<string, string> = {};
for (const entry of entries) {
  if (!entry.isFile()) continue;
  const absolute = join(entry.parentPath, entry.name);
  const relative = absolute.slice(skillDir.length + 1);
  files[relative] = await Bun.file(absolute).text();
}

const sortedPaths = Object.keys(files).sort();
if (sortedPaths.length === 0) {
  console.error(
    'No files found in skill/ — refusing to generate an empty module.',
  );
  process.exit(1);
}

const lines = [
  '// Generated by scripts/generate-embedded-skills.ts from skill/ — do not edit.',
  '// Regenerate with: pnpm run generate:skills',
  '',
  'export const EMBEDDED_SKILLS: Record<string, string> = {',
  ...sortedPaths.map(
    (path) => `  ${JSON.stringify(path)}: ${JSON.stringify(files[path])},`,
  ),
  '};',
  '',
];

await Bun.write(outPath, lines.join('\n'));
console.log(`Embedded ${sortedPaths.length} files into ${outPath}`);
